const paperNotes = {
  paper: {
    title: "A research-grounded starting point",
    text: "This prototype uses Westley et al. (2026), a case study of how cognitive, positive, and industrial psychology can inform the design of student wellness check-ins. The demo guidance is prewritten from the paper; it is not generated by a live AI system."
  },
  perma: {
    title: "PERMA and positive emotions",
    text: "On printed page 5, Section 3.3 frames positive psychology through flourishing, including PERMA: positive emotions, engagement, relationships, meaning, and accomplishment. The paper also describes reflective questions that invite students to recognize positive experiences."
  },
  table: {
    title: "A short check-in can lower friction",
    text: "Table 1 on printed page 5 describes concise check-ins that take 2–5 minutes and present one question at a time. The authors connect that pattern with attention, retention, accessibility, usability, engagement, and accomplishment."
  },
  design: {
    title: "Design for a real student context",
    text: "On printed page 8, the authors discuss how concise, clear check-ins support usability and accessibility, and how reflective prompts can help students notice positive experiences. A student wellness feature should be designed with students’ needs and context in mind."
  }
};

const $ = (selector) => document.querySelector(selector);
const $$ = (selector) => [...document.querySelectorAll(selector)];
const workArea = $("#work-area");
const emptyState = $("#empty-state");
const progressBar = $("#progress-bar");
const progressNumber = $("#progress-number");
const citationDialog = $("#citation-dialog");
let started = false;
let firstStepDone = false;
let selectedFramework = "PERMA";
let selectedFeature = "Short, one-question check-ins";
let featureChosen = false;
let toastTimer;

function showToast(message) {
  const toast = $("#toast");
  toast.textContent = message;
  toast.classList.add("show");
  clearTimeout(toastTimer);
  toastTimer = setTimeout(() => toast.classList.remove("show"), 2300);
}

function openCitation(key) {
  const note = paperNotes[key] || paperNotes.paper;
  $("#citation-title").textContent = note.title;
  $("#citation-text").textContent = note.text;
  citationDialog.showModal();
}

function updateProgress() {
  const draftText = $("#proposal-input").value.trim();
  const drafted = draftText.length >= 35 && !/\[[^\]]+\]/.test(draftText);
  const completedCount = (firstStepDone ? 1 : 0) + (firstStepDone && featureChosen ? 1 : 0) + (firstStepDone && featureChosen && drafted ? 1 : 0);
  const percent = Math.round(completedCount / 3 * 100);
  progressBar.style.width = `${percent}%`;
  progressNumber.textContent = `${percent}%`;
  $("#step-one").classList.toggle("completed", firstStepDone);
  $("#step-one").classList.toggle("current", !firstStepDone);
  $("#step-one-status").innerHTML = firstStepDone ? "✓" : "<span>1</span>";
  $("#step-two").classList.toggle("completed", firstStepDone && featureChosen);
  $("#step-two").classList.toggle("current", firstStepDone && !featureChosen);
  $("#step-two-status").innerHTML = firstStepDone && featureChosen ? "✓" : "<span>2</span>";
  $("#step-three").classList.toggle("completed", firstStepDone && featureChosen && drafted);
  $("#step-three").classList.toggle("current", firstStepDone && featureChosen && !drafted);
  $("#step-three-status").innerHTML = firstStepDone && featureChosen && drafted ? "✓" : "<span>3</span>";
  if (firstStepDone) $("#step-two").scrollIntoView({ behavior: "smooth", block: "nearest" });
}

$("#breakdown-button").addEventListener("click", () => {
  if (!started) {
    started = true;
    workArea.hidden = false;
    emptyState.hidden = true;
    $("#breakdown-button").innerHTML = '<span class="sparkle">✓</span><span>Plan ready</span><span class="button-arrow">↗</span>';
    $("#breakdown-button").setAttribute("aria-label", "Your plan is ready");
    $("#work-area").scrollIntoView({ behavior: "smooth", block: "start" });
  }
});

$$("[data-citation]").forEach((button) => button.addEventListener("click", () => openCitation(button.dataset.citation)));
$("#dialog-close").addEventListener("click", () => citationDialog.close());
citationDialog.addEventListener("click", (event) => {
  if (event.target === citationDialog) citationDialog.close();
});

$$(".framework-choice").forEach((button) => button.addEventListener("click", () => {
  selectedFramework = button.dataset.framework;
  $$(".framework-choice").forEach((choice) => {
    const selected = choice === button;
    choice.classList.toggle("selected", selected);
    choice.setAttribute("aria-pressed", String(selected));
  });
  const prompts = {
    PERMA: "Page 5 introduces PERMA: Positive Emotions, Engagement, Relationships, Meaning, and Accomplishment. How could a check-in question help a student notice one positive moment during exam stress?",
    Cognitive: "Page 5 connects check-ins with attention and metacognition. What is one simple question that could help a student pause and notice how they are learning during exam week?",
    Industrial: "The paper links clear, concise check-ins with usability and accessibility. What could make a wellness check-in feel easier for a busy student to use?"
  };
  $("#coach-question").textContent = prompts[selectedFramework];
}));

$$(".feature-choice").forEach((button) => button.addEventListener("click", () => {
  selectedFeature = button.dataset.feature;
  featureChosen = true;
  $$(".feature-choice").forEach((choice) => choice.classList.toggle("selected", choice === button));
  updateProgress();
}));

$("#suggestion-button").addEventListener("click", () => {
  $("#student-response").value = "Ask the student to name one small win from today before showing their task list.";
  $("#student-response").focus();
});

$("#complete-button").addEventListener("click", () => {
  const response = $("#student-response").value.trim();
  if (response.length < 8) {
    $("#student-response").focus();
    showToast("Add one small thought to save your first step.");
    return;
  }
  firstStepDone = true;
  $("#completion-message").hidden = false;
  $("#complete-button").innerHTML = "<span>First step saved</span><span>✓</span>";
  $("#complete-button").disabled = true;
  $("#complete-button").style.opacity = ".72";
  updateProgress();
  showToast("One idea down. You’ve got a starting point.");
});

$("#proposal-input").addEventListener("input", () => {
  const value = $("#proposal-input").value.trim();
  const drafted = value.length >= 35 && !/\[[^\]]+\]/.test(value);
  $("#draft-status").textContent = drafted ? "Good start · draft saved here" : "Your words, your idea";
  updateProgress();
});

$("#draft-button").addEventListener("click", () => {
  const input = $("#proposal-input");
  if (input.value.trim().length < 20) {
    input.value = `Using ${selectedFramework}, I could add [describe your check-in feature]. It could help students [explain the small benefit to them].`;
    input.dispatchEvent(new Event("input", { bubbles: true }));
    showToast("A sentence scaffold is ready for you to complete in your own words.");
  } else {
    showToast("Your draft is ready to shape in your own words.");
  }
});

$("#proposal-input").addEventListener("focus", () => {
  if (!firstStepDone) showToast("Start with the 5-minute thought, then shape your proposal.");
}, { once: true });
